GET http://localhost:5110/players

###
GET http://localhost:5110/players/4

###
POST http://localhost:5110/players
Content-Type: application/json

{
    "Name": "Gordie Howe",
    "Goals": 801,
    "Assists": 1049,
    "TotalPoints": 1850
}

###
PUT http://localhost:5110/players/5
Content-Type: application/json

{
    "Name": "Ron Francis",
    "Goals": 549,
    "Assists": 1249,
    "TotalPoints": 1798
}

###
DELETE http://localhost:5110/players/3